### PR TITLE
gitlab #2 - moved some settings as advanced settings.

### PR DESCRIPTION
**Pull request by jpahullo**
Here are the configuration of all plugin settings using the setAdvanced flag.

Screenshots:

1. Administration:
image
1. Module settings without capability (so, having visible some of the settings):
image
1. Module settings with capability, and having visible as advanced those settings:
image

Hoping this matches what we talked about last days.

Thanks for your time,

Jordi

### CODE REVIEW

**Comment by danmarsden** [comment]
that's definitely closer - thanks! 
although as this also changes which elements are flagged as advanced and which are normal elements we may need to implement the abliity for an admin to decide which elements are advanced and which are normal - (like the scorm code I linked to above) because what works for you may not work for all sites. If you don't have time to work on this further let me know. Thanks!

**Comment by jpahullo** [comment]
Hi @danmarsden !

From your comments, what I can get for what settings should be is the following:

1. Urkund settings for administrators should include the current settings and an additional select with multiple selection to choose which are going to be considered as advanced.
1. Urkund settings at the module settings will show the following:
 * Only the mandatory settings, if the teacher does not have the capability, or
 * The whole set of urkund settings (excluding the select with multiple selection), with the advanced settings as expected.

Is that right?

Thank you!

**Comment by danmarsden** [comment]
yeah - that sounds right - thanks!

**Comment by jpahullo** [comment]
Ok! I'll put my hands on this the next days. Thanks for the confirmation. I will update this PR with the last changes.

Thanks!

**Comment by jpahullo** [comment]
I will deliver some changes today. They will have the following options:

1. Administration settings, with an additional field to select which settings are to be considered as `advanced`.
 * image
 * An example of selection of 4 fields: 
image
1. After selecting the advanced items, in a new task form we can see the advanced elements of the form:
 * 
image
 * And another example: 
image

**Comment by jpahullo** [comment]
Oh... before accepting it, I will push all changes in a single commit. Now, I leave it as it is to help you on the peer review.

Jordi

**Comment by jpahullo** [comment]
Hi @danmarsden,

How things are going with this PR? Is there something else I should do? Time goes by. Any feedback please?

Thanks for your time,

Jordi

**Comment by danmarsden** [comment]
Sorry Jordi - I've been away on Annual Leave, just got back but there's quite a large backlog of e-mail/work to go through. I'll try to take a look at it next week, but feel free to bug me again if I haven't merged it. - thanks again!

**Comment by jpahullo** [comment]
Hi Dan! 

No problem at all. We'll talk about it next week. Have a warm welcome.

Regards,

Jordi

**Comment by danmarsden** [comment]
finally got a chance to take a proper look at this today - I'm seeing this error on a site upgraded to use your patch:
<b>Notice</b>:  Undefined index: urkund_advanceditems in <b>/plagiarism/urkund/lib.php</b> on line <b>503</b>

we probably need to handle that better - I'd probably add an upgrade step to set advanceditems to use the same advanced options as it was before the patch.

also would be good to fix up the errors that the travis ci build finds above:

FILE: /home/travis/build/moodle/plagiarism/urkund/lib.php
---------------------------------------------------------------------------------------------------
FOUND 1 ERROR AND 4 WARNINGS AFFECTING 3 LINES
502 | WARNING | [ ] Inline comments must start with a capital letter, digit or 3-dots sequence
502 | WARNING | [ ] Inline comments must end in full-stops, exclamation marks, or question marks
509 | WARNING | [ ] Inline comments must start with a capital letter, digit or 3-dots sequence
509 | WARNING | [ ] Inline comments must end in full-stops, exclamation marks, or question marks
816 | ERROR   | [x] Functions must not contain multiple empty lines in a row; found 2 empty lines

The last one there is the reason for the Travis build failure but the other warnings there would be good to fix too.

Travis-ci checks also includes a PHP mess detector check which throws a bunch of violations with existing code (just ignore those) 

let me know if you won't be able to make those final changes and I'll find some time to do it. Thanks!

**Comment by jpahullo** [comment]
Hi Dan!

Thank you so much for your time.

I'll consider two points:

1. Fix errors during upgrade. I'll check what is necessary, and I'll check if some step at upgrade.php is necessary to solve that.
1. Fix TravisCI errors as you suggested.

I suppose that during this week or next, I'll be back to you with updated PR.

Keep in touch!

Jordi

**Comment by jpahullo** [comment]
I had too much work lately. I expect to work on this next week or so.

Thanks for your time!

**Comment by jpahullo** [comment]
I have pushed a first set of changes solving the travisCI issues. Now I've just pushed the last changes to solve warning during the upgrade process of the plugin.

I run this upgrade process in local and it didn't show me any warning. I will wait to pass travisCI. Then, I will set this PR as pending for your revision.

Thank you so much for your time and sorry for being late updating this PR. I had so much work on my institution.

**Comment by jpahullo** [comment]
@danmarsden, 

All checks have been passed. And also, I think, all requirements you set are met now.

Let me know if you need something else.

Regards,

Jordi

**Comment by danmarsden** [comment]
so close! - problem is that we need to merge into the "master" branch first - rather than the specific 3.0 branch. I've swapped that over to the master branch and it's finding a few conflicts - I'll find some time next week to fix that up and merge unless you beat me to it! - Thanks heaps! :-)

**Comment by jpahullo** [comment]
Thanks for your answer @danmarsden !

We'll keep in contact. I'll try to do that also for the next week.

Hugs!

Jordi

**Comment by jpahullo** [comment]
I build the new PR https://github.com/danmarsden/moodle-plagiarism_urkund/pull/103 to merge it into master.

Please, since we use Moodle 3.0, could you merge this PR for Moodle 3.0 and then the other PR for the master? I mean, we need in our institution to have this included into original repository and compatible version to be installed into our Moodle.

Do you think it will be possible?

Thanks in advance,

Jordi

**Comment by danmarsden** [comment]
closing this one as it conflcts and can't be automatically merged - will merge in the master one and cherry-pick across when finished testing - thanks!

**Pull request closed without merging**
