### PR TITLE
2 to master

### PR DESCRIPTION
**Pull request by jpahullo**
This is what @danmarsden asked to merge https://github.com/danmarsden/moodle-plagiarism_urkund/pull/98 into master.

We'll keep in contact.

Jordi

### CODE REVIEW

**Comment by jpahullo** [comment]
I saw errors for incompatibility of the code due to using PHP 5.6 while expecting PHP 7. And other errors under PHP 7 due to behat tests.

**Comment by jpahullo** [comment]
Thank you for accepting our work! Good news for all!

Regards,

Jordi

**Comment by danmarsden** [comment]
I've also been asked to improve the default handling a bit more, allowing different defaults to be used in assignment/workshop/forum. I expect this will end up causing a rewrite of how the settings are currently being handled but I'll make sure I keep the functionality you have also added. Thanks!

**Comment by jpahullo** [comment]
Uoh! Ok! Thank YOU so much!

**Comment by danmarsden** [comment]
I've just pushed this change into the 3.0->master branches here in github - let me know if you get a chance to test it - thanks!

**Comment by jpahullo** [comment]
That's a great job. What a master! I'm in vacations. As soon as I could test it at work, I'll tell you. Thanks!

**Comment by jpahullo** [comment]
Hi!

You did a great job, moving backwards so many changes. We now in Moodle 3 have separated settings for each kind of activity, and solved the issue on text only submission. Fantastic!

Thank you so much!!!

Now that we have it in production, somehow appeared this error  #106. And in #107 you have the proposed solution.

Thank you for your time.

Jordi

**Pull request merged**
